### ISSUE TITLE
Add visual indicators about a Pilet's origin

### ISSUE THREAD

**Issue by manuelroemer** [smapiot/piral-inspector#12]
It would be fantastic if the extension was able to give developers hints about a pilet's origin. This can, for example, be used to quickly locate the source package of an extension and thus significantly reduces the time that one might spend looking through the code.

The following image demonstrates a potential way to implement this:
![grafik](https://user-images.githubusercontent.com/30902964/83016974-1a136680-a023-11ea-8a28-1e8e72dba019.png)
This only shows the general concept. In the real implementation, every single pilet/extension should be highlighted.
If this approach is used, the following requirements should be a good starting point:
* Each pilet should have a designated color which is reused.
* The origin (i.e. the text) should be displayed "intelligently", meaning that it might, for example, be hidden for very small elements.
* The entire visualization should be toggleable via the extension's settings. 

*For the image above, code similar to this was injected into the DOM:
`position: absolute; right: 0; top: 0; font-size: 10px; background: green; color: white`.*

**Comment by FlorianRappl** [comment]
Sounds just great!

Will be covered in the next version.
