### ISSUE TITLE
Font color not visible in darkmode (Chrome)

### ISSUE THREAD

**Issue by lamson-dev** [smapiot/piral-inspector#13]
See images below:
<img width="500" alt="Screen Shot 2020-06-05 at 6 15 07 PM" src="https://user-images.githubusercontent.com/1919336/83932671-0d94b980-a759-11ea-8b3c-5d286b685923.png">
<img width="500" alt="Screen Shot 2020-06-05 at 6 15 22 PM" src="https://user-images.githubusercontent.com/1919336/83932673-0f5e7d00-a759-11ea-8386-974546693401.png">
<img width="500" alt="Screen Shot 2020-06-05 at 6 16 44 PM" src="https://user-images.githubusercontent.com/1919336/83932674-0f5e7d00-a759-11ea-8507-ad669c105c4a.png">
<img width="500" alt="Screen Shot 2020-06-05 at 6 17 13 PM" src="https://user-images.githubusercontent.com/1919336/83932675-0ff71380-a759-11ea-850f-e58efe9c41f2.png">

**Comment by FlorianRappl** [comment]
Its a good point - thanks for identifying this. We'll take care of it asap.

We have the 0.6 anyway on the list with cool feature #12 (its done).

Should be ready to ship in the next couple of days.
