### ISSUE TITLE
Small UX Improvements: Settings and Toolbar

### ISSUE THREAD

**Issue by manuelroemer** [smapiot/piral-inspector#25]
I have a few suggestions potentially improving the extension's UX - feel free to discuss!

### Settings: Grouping Settings
Currently, all settings are displayed as one consecutive, unordered list:
![grafik](https://user-images.githubusercontent.com/30902964/213690507-bbbfc0e8-6506-4d8a-9a87-3cb44f9c7c78.png)

This could be improved by grouping the entries into groups. Right now, I could imagine the following structure:
- Application/Page Settings:
  - State container logging
  - Load available pilets
  - Full refresh on change
  - Enable extension catalogue
- Extension Settings:
  - Visualize component origins _(debatable whether this belongs here ❓)_
  - Persist settings
  - Switch to dark mode

### Settings: Pilet-Only Settings
Some settings only have an effect when debugging pilets. It would be cool if this was indicated directly in the settings modal (otherwise, we only have the external documentation).

This could be tackled in many different ways, some more difficult than others, e.g. by:
- just adding a text/note explaining this
- adding an icon
- adding an extra group for pilet-only settings (see above)
- very cool, but potentially hard (?): detecting whether a setting would have an effect on the current page and, if not, dynamically displaying a :warning: warning icon next to the entry explaining the situation

### Toolbar Button Tooltips
The buttons in the toolbar (Settings/Visualize Component Origins) only display an icon, but no helper text. For the settings the functionality is probably obvious, but overall, having a tooltip with a description of the button's effect would be nice to have.
![grafik](https://user-images.githubusercontent.com/30902964/213692677-fec766b6-903b-498b-ba58-26b3c66b4917.png)

### Monospaced Font for Parameter Inputs
Inputs where you can enter JSON-like content would benefit from a monospaced font. Additional points could be given for replacing the input with a fully-fledged JSON editor component.
![grafik](https://user-images.githubusercontent.com/30902964/213696269-a19c06f0-add5-4399-b683-971b2b1c908c.png)

**Comment by FlorianRappl** [comment]
I'd say these are all great changes - and I've assigned you to work on them (just let's talk *when* we do them - but if you feel like these are a "snack" then snack it :D).
